site:
  name: TapRebook
  site: 'https://taprebook.com'
  base: '/'
  trailingSlash: false

  # Add this only after Google Search Console gives you a value.
  # Leave blank or delete this line until then.
  googleSiteVerificationId:

# Default SEO metadata
metadata:
  title:
    default: TapRebook
    template: '%s — TapRebook'
  description: "Automated WhatsApp reception that keeps schedules full—reduce no-shows, speed up scheduling/rescheduling, and streamline patient/customer messaging."
  robots:
    index: true
    follow: true
  openGraph:
    site_name: TapRebook
    images:
      - url: '~/assets/images/default.png'
        width: 1200
        height: 628
    type: website
  twitter:
    handle:
    site:
    cardType: summary_large_image

i18n:
  language: en
  textDirection: ltr

apps:
  blog:
    isEnabled: true
    postsPerPage: 6

    post:
      isEnabled: true
      permalink: '/%slug%'
      robots:
        index: true

    list:
      isEnabled: true
      pathname: 'blog'
      robots:
        index: true

    category:
      isEnabled: true
      pathname: 'category'
      robots:
        index: true

    tag:
      isEnabled: true
      pathname: 'tag'
      robots:
        index: false

    isRelatedPostsEnabled: true
    relatedPostsCount: 4

analytics:
  vendors:
    googleAnalytics:
      id: null # e.g., "G-XXXXXXXXXX" when you have one

ui:
  theme: 'system' # "system" | "light" | "dark" | "light:only" | "dark:only"

