site:
  name: TapRebook
  site: 'https://taprebook.com'
  base: '/'
  trailingSlash: false

metadata:
  title:
    default: "TapRebook — WhatsApp coordination for businesses"
    template: "%s • TapRebook"
  description: "Automate reminders, confirmations, queue updates, and follow-ups on WhatsApp."
  robots:
    index: true
    follow: true
  openGraph:
    images:
      - url: "https://taprebook.com/images/taprebook-og.png"
        width: 1200
        height: 630
  twitter:
    cardType: "summary_large_image"
    image: "https://taprebook.com/images/taprebook-og.png"

i18n:
  language: en
  textDirection: ltr

header:
  nav:
    - text: Solutions
      ariaLabel: "TapRebook modules"
      links:
        - text: Reception
          href: /modules/reception/
        - text: Labs
          href: /modules/labs/
        - text: Pharma
          href: /modules/pharma/
        - text: DentalLab
          href: /modules/dentallab/
        - text: Stay
          href: /modules/stay/
        - text: Campus
          href: /modules/campus/
        - text: Queue
          href: /modules/queue/
    - text: Pricing
      href: /pricing/
    - text: About
      href: /about/
    - text: Contact
      href: /contact/
  cta:
    label: "Book a demo"
    href: /contact/

apps:
  blog:
    isEnabled: true
    postsPerPage: 6
    post:
      isEnabled: true
      permalink: '/%slug%'
      robots:
        index: true
    list:
      isEnabled: true
      pathname: 'blog'
      robots:
        index: true
    category:
      isEnabled: true
      pathname: 'category'
      robots:
        index: true
    tag:
      isEnabled: true
      pathname: 'tag'
      robots:
        index: false
    isRelatedPostsEnabled: true
    relatedPostsCount: 4

analytics:
  vendors:
    googleAnalytics:
      id: null

ui:
  theme: 'system'

footer:
  message: "© {{2025}} TapRebook. All rights reserved."
  links:
    - text: Pricing
      href: /pricing/
    - text: Contact
      href: /contact/
  contact:
    address: "CCR-3 Padamughal, Kakkanad, Kerala 682030"
    email: "hello@taprebook.com"
  socials:
    - name: WhatsApp
      href: "https://wa.me/15303018709"
